// ui actions
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
// stores actions
export const UPDATE_STORES = 'UPDATE_STORES';
export const SET_ACTIVE_STORE = 'SET_ACTIVE_STORE';
export const UPDATE_CATALOG = 'UPDATE_CATALOG';
export const UPDATE_PRODUCTS_IN_STOCK = 'UPDATE_PRODUCTS_IN_STOCK';
export const SET_PRODUCTS_IN_STOCK = 'SET_PRODUCTS_IN_STOCK';
// stores.cart actions
export const UPDATE_PRODUCT_QUANTITY_IN_CART = 'UPDATE_PRODUCT_QUANTITY_IN_CART';
export const CLEAR_CART = 'CLEAR_CART';
