export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const UPDATE_STORES = 'UPDATE_STORES';
export const ACTIVATE_STORE = 'ACTIVATE_STORE';
export const SET_ACTIVE_STORE = 'SET_ACTIVE_STORE';